kind: pipeline
type: docker
name: default

steps:
- name: greeting
  image: alpine
  commands:
  - echo hello
  - echo world
- name: build
  image: alpine
  commands:
  - echo Building...
  when:
    branch:
    - develop
 
---
kind: pipeline
type: docker
name: publish

steps:
- name: greeting
  image: alpine
  commands:
  - echo hello publish
- name: docker  
  image: plugins/docker
  settings:
    auto_tag: true
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: ducdung8491/drone-hello
- name: notify
  image: plugins/slack
  settings:
    channel: #development
    webhook:
      from_secret: slack_webhook 
    image_url: https://unsplash.it/256/256/?random
