kind: pipeline
type: docker
name: default

steps:
- name: greeting
  image: alpine
  commands:
  - echo hello
  - echo world
- name: build
  image: alpine
  commands:
  - echo Building...
  when:
    branch:
    - develop
 
---
kind: pipeline
type: docker
name: publish

steps:
- name: greeting
  image: alpine
  commands:
  - echo hello publish
