kind: pipeline
type: docker
name: default

steps:
- name: greeting
  image: alpine
  commands:
  - echo hello
  - echo world
- name: build
  image: alpine
  commands:
  - echo Building...
  when:
    branch:
    - develop
 
---
kind: pipeline
type: docker
name: publish

steps:
- name: greeting
  image: alpine
  commands:
  - echo hello publish
- name: notify
  image: plugins/slack
  settings:
    channel: #development
    webhook:
      from_secret: slack_webhook
    image_url: https://unsplash.it/256/256/?random
