kind: pipeline
type: docker
name: default

steps:
- name: greeting
  image: alpine
  commands:
  - echo hello
  - echo world
- name: build
  image: alpine
  commands:
  - echo Building...
  when:
    branch:
    - develop
 
---
kind: pipeline
type: docker
name: publish

steps:
- name: greeting
  image: alpine
  commands:
  - echo hello publish
- name: notify
  image: plugins/slack
  settings:
    channel: #development
    webhook: https://hooks.slack.com/services/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
